epochs: 10
grad_clip: 5.0
log_frequency: 100

model:
  name: ResNetMTL_binary
  n_tasks: 40

criterion:
  name: BCEWithLogitsLoss
  # reduction: None

pos_weight: [7.954723001595424, 2.7610333194694765, 0.9469397031207015, 3.8909254807692304, 42.83786695394559, 5.593882924853149, 3.1509193379746514, 3.2453248480738637, 3.183673469387755, 5.707462809576792, 18.46543889021765, 3.9038925042178834, 5.960147096553494, 16.336244541484714, 20.499141460837407, 14.470962836232298, 14.746348070039664, 22.603538283062644, 1.6020302134121973, 1.2101975694208704, 1.384524106004893, 1.0738730474224703, 23.506172839506174, 7.626318299856909, 0.19878626297144622, 2.5307260146200736, 22.236259814418275, 2.6295321767827677, 11.482361963190185, 14.465083135391925, 16.77741371778069, 1.084656762295082, 3.7948272306831234, 2.131276210996114, 4.360977537711613, 19.247543226769498, 1.1294660962622813, 7.235681036227485, 12.689655172413794, 0.2837965738082469]

optimizer:
  name: Adam
  lr: 1.e-3
  weight_decay: 1.e-4

scheduler:
  name: MultiStepLR
  milestones: [6,8]
  gamma: 0.1

dataset:
  name: DatasetGenerator
  train_batch_size: 128
  eval_batch_size: 128
