model:
  name: ResNet18DAE
  num_classes: 2
  stem_end_block: 9
  attr_num: 40
  epsilon: 0.0314
  emb_p_spatial_dim: 35
  sample_wise: True
  z_only: False

optimizer:
  name: Adam
  lr: 1.e-3
  weight_decay: 1.e-4

scheduler:
  name: MultiStepLR
  milestones: [60,80]
  gamma: 0.1