epochs: 10
grad_clip: 5.0
log_frequency: 100

model:
  name: ResNetMTL_binary
  n_tasks: 40

criterion:
  name: BCEWithLogitsLoss
  # reduction: None

optimizer:
  name: Adam
  lr: 1.e-3
  weight_decay: 1.e-4

scheduler:
  name: MultiStepLR
  milestones: [6,8]
  gamma: 0.1

dataset:
  name: DatasetGenerator
  train_batch_size: 128
  eval_batch_size: 128
