epochs: 60
grad_clip: 5.0
log_frequency: 100

model:
  name: ResNetMTL
  n_tasks: 3
  task_outputs: [9, 5, 2]

criterion:
  name: MultiMadrysLossUnsupervisedPGD
  epsilon: 0.007843125
  perturb_steps: 10
  step_size: 0.0019107843

optimizer:
  name: Adam
  lr: 1.e-3
  weight_decay: 1.e-4

scheduler:
  name: MultiStepLR
  milestones: [45, 54, 60]
  gamma: 0.1

dataset:
  name: DatasetGenerator
  train_batch_size: 128
  eval_batch_size: 128
